version: '3.7'
services:
    database:
        image: 'postgres:16'
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_USER: root
            POSTGRES_DB: task-platform-backend
        ports:
            - '5432:5432'
